package org.example;

public enum TipoPokeball {
    POKEBALL,HONORBALL,SUPERBALL,ULTRABALL,MASTERBALL,SAFARIBALL,
    NIVELBALL,CEBOBALL,KUNABALL,AMIGOBALL,AMORBALL,PESOBALL,RAPIDBALL,
    COMPETIBALL,ACOPIOBALL,TURNOBALL,
    NIDOBALL,MALLABALL,BUCEOBALL,LUJOBALL,SANABALL,
    VELOZBALL,OCASOBALL,GLORIABALL,PARQUEBALL;
}
