package org.Proyecto_Pokemon.model;

public enum Status {
    NORMAL, ENVENENADO, QUEMADO, CONGELADO, PARALIZADO, GRAVEMENTE_ENVENENADO, DEBILITADO,
    DORMIDO, CONFUSO, MALDITO, AMEDRENTADO, ATRAPADO, ENAMORADO,
    DRENADORAS, CENTRO_ATENCION, CANTO_MORTAL, SOMNOLIENTO,
    DESCANSANDO, AGOTADO;



}
